### PR TITLE
Add npm/bower support

### LINKED ISSUE #9: npm?
Hi,
Have you thought about releasing ccapture on npm? It would make it much easier to include it in modern projects.

### PR DESCRIPTION
**Pull request by timseverien**
Fixes #9. You still have to do some stuff, as I don’t feel I’m the person to manage versions or whatever.

1.  Add git tag (eg. `git tag 1.0.0`)
2. Update `version` in package.json and bower.json to whatever version you chose in step 1
3. `npm publish`
4. `bower register ccapture.js git@github.com:spite/ccapture.js.git`

### CODE REVIEW

**Comment by spite** [comment]
Ok! After updating to the new version, I can take a look at this one 😅

I see that this PR adds support for being in npm and being registered in bower (if anyone is still using it), but shouldn't the lib be also CommonJS/Require/ES6 module compatible?

**Comment by timseverien** [comment]
Bower is installed quite a lot still, [according to npm](https://www.npmjs.com/package/bower). I’m just going to assume I’m not the only one using it 😝

As for module compatibility: not per-se. Bower does allow modules to define a global variable. I’ve configured as such, given that ccapture exposes a global variable.

```json
"moduleType": [
  "globals"
]
```

**Comment by spite** [comment]
I've added npm support, published here https://www.npmjs.com/package/ccapture.js

Could you take a look and see if it works as expected, and if support for bower can be added back? I'm sorry I made the PR impossible to merge, but I wanted to understand what the npm support was really doing.

**Comment by timseverien** [comment]
@spite Updated repository, and updated bower.json so it matches your edits in package.json 👍

**Comment by spite** [comment]
Merged! Do I need to run anything, or re-publish the module? I imagine bower reads directly from the GH repo?

**Comment by spite** [comment]
Seems to be working. I've bower register'd it and i can install it. Thanks, @timseverien !

**Comment by timseverien** [comment]
Yeah. Whenever you want to release a new version, you can use npm for that: `npm version <versionIncrement>`, where `<versionIncrement>` is `major`, `minor`, or `patch`.

That line will update your package.json version and add a git tag. After that, run `npm publish` to publish the new version.

```shell
# Show last version number
git tag | tail -n 1
# v1.0.3

# Update version
npm version patch

# Show last number version again
git tag | tail -n 1
# v1.0.4

npm publish
```

**Comment by spite** [comment]
Thanks! I've done that to get it published (npm is v1.0.3). 
Question is how to keep the bower version up to date? Does it read the version automatically, do i have to `bower version`?

**Comment by timseverien** [comment]
Bower updates automagically 🦄

**Pull request merged**
